### PR TITLE
Fix invalid charmcraft yaml

### PR DESCRIPTION
**Pull request by mina1460**
We had an invalid charmcraft.yaml file that broke the charmcraft pack command

Note:
This is also a perfectly valid charmcraft.yaml file that we can use to enable building our charms for other architectures, which would be really good. I left it out intentionally to not slow down charmcraft pack,  if you think we need it, I can update the PR.
```
type: charm
bases:
  - build-on:
    - name: ubuntu
      channel: "22.04"
    run-on:
    - name: "ubuntu"
      channel: "22.04"
      architectures: [amd64, arm64, ppc64el, s390x]
    - name: "ubuntu"
      channel: "23.10"
      architectures: [amd64, arm64, ppc64el, s390x]
    - name: "ubuntu"
      channel: "23.04"
      architectures: [amd64, arm64, ppc64el, s390x]
    - name: "ubuntu"
      channel: "20.04"
      architectures: [amd64, arm64, ppc64el, s390x]
```

### CODE REVIEW

**Review by kian99 — COMMENTED** [review]
I'm not sure I agree with the new format, interesting that the form that was working before is now rejected by charmcraft. But can't we specify one build-on and multiple run-on as before?

**Comment by mina1460** [comment]
@kian99 I think the issue is that we had more than 1 build-on

**Comment by kian99** [comment]
I was able to build the charm from `main`.
```
livepatch-k8s-operator$ charmcraft pack
Created 'canonical-livepatch-server-k8s_ubuntu-20.04-amd64_ubuntu-22.04-amd64.charm'.                                                                          
Charms packed:                                                                 
    canonical-livepatch-server-k8s_ubuntu-20.04-amd64_ubuntu-22.04-amd64.charm 
```

**Comment by kian99** [comment]
I suspect this [action's failure](https://github.com/canonical/livepatch-k8s-operator/actions/runs/7476942761/job/20348495038) might be doing to something besides the charmcraft.yaml file.

**Pull request closed without merging**
